### ISSUE TITLE
A segunda issue - atualizar o readme. 

### ISSUE THREAD

**Issue by gabicantarini** [mariojrcarvalho/portifolio#2]
Como recomendações é possível adicionar imagens, mais detalhes do projeto, o que você aprendeu com ele, quais foram as dificuldades, adicionar badges e ser criativo para adicionar mais do seu estilo.

**Comment by mariojrcarvalho** [comment]
Oi Gabi, obrigado pelo conselho, tenho estudado e visto o quanto é importante mesmo ter um readme bom
